# Generated by Django 3.1.7 on 2022-06-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='programme',
            name='fin',
            field=models.TimeField(default='23:52:01'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='fin',
            field=models.TimeField(default='23:52:01'),
        ),
    ]
