# Generated by Django 3.1.7 on 2022-03-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_article_num_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='num_page',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
