# Generated by Django 3.1.7 on 2022-06-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220608_2352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='radio',
        ),
        migrations.AlterField(
            model_name='programme',
            name='fin',
            field=models.TimeField(default='19:00:03'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='fin',
            field=models.TimeField(default='19:00:03'),
        ),
    ]
