# Generated by Django 3.1.7 on 2022-06-13 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220613_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourRadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=20, unique=True)),
                ('image', models.ImageField(default='', upload_to='media')),
            ],
        ),
        migrations.AlterField(
            model_name='programme',
            name='fin',
            field=models.TimeField(default='19:15:56'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='fin',
            field=models.TimeField(default='19:15:56'),
        ),
        migrations.CreateModel(
            name='PubliciteRadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('son', models.FileField(blank=True, default='', null=True, upload_to='media')),
                ('debut', models.TimeField()),
                ('fin', models.TimeField(default='19:15:56')),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('encombrement', models.IntegerField(blank=True, null=True)),
                ('ecran', models.IntegerField()),
                ('language', models.CharField(choices=[('AR', 'arabe'), ('FR', 'francais'), ('AF', 'arabe + francais')], default='', max_length=2)),
                ('message', models.CharField(default='', max_length=12000)),
                ('confirmed', models.BooleanField(default=False)),
                ('annonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.annonceur')),
                ('famille', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.famille')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jour')),
                ('marche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marche')),
                ('marque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marque')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.produit')),
                ('secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.secteur')),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.segment')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammeRadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=1200)),
                ('debut', models.TimeField()),
                ('fin', models.TimeField(default='19:15:56')),
                ('jour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jourradio')),
            ],
        ),
        migrations.AddField(
            model_name='jourradio',
            name='chaine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.radio'),
        ),
    ]
