# Generated by Django 3.1.7 on 2022-06-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220329_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourAfficheur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='afficheur',
            name='date_creation',
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='Nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='programme',
            name='message',
            field=models.CharField(default='', max_length=1200),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='message',
            field=models.CharField(default='', max_length=12000),
        ),
    ]
