# Generated by Django 3.1.7 on 2022-06-05 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220605_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='afficheur',
            name='jour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.jourafficheur'),
        ),
    ]
