# Generated by Django 3.1.7 on 2022-06-13 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220613_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='fin',
            field=models.TimeField(default='20:00:52'),
        ),
        migrations.AlterField(
            model_name='programmeradio',
            name='fin',
            field=models.TimeField(default='20:00:52'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='fin',
            field=models.TimeField(default='20:00:52'),
        ),
        migrations.AlterField(
            model_name='publiciteradio',
            name='fin',
            field=models.TimeField(default='20:00:52'),
        ),
        migrations.AlterField(
            model_name='publiciteradio',
            name='jour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jourradio'),
        ),
    ]
