# Generated by Django 3.1.7 on 2022-06-05 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_afficheur_jour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afficheur',
            name='jour',
        ),
        migrations.RemoveField(
            model_name='pub',
            name='date_creation',
        ),
        migrations.AddField(
            model_name='pub',
            name='jour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.jourafficheur'),
        ),
    ]
