# Generated by Django 3.1.7 on 2022-06-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220613_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.famille'),
        ),
        migrations.AddField(
            model_name='article',
            name='marche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marche'),
        ),
        migrations.AddField(
            model_name='article',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.secteur'),
        ),
        migrations.AddField(
            model_name='article',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.segment'),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='service',
            field=models.CharField(choices=[('J', 'Journal'), ('P', 'Panneau'), ('C', 'Chaine'), ('R', 'Radio')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='programme',
            name='fin',
            field=models.TimeField(default='20:18:08'),
        ),
        migrations.AlterField(
            model_name='programmeradio',
            name='fin',
            field=models.TimeField(default='20:18:08'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='fin',
            field=models.TimeField(default='20:18:08'),
        ),
        migrations.AlterField(
            model_name='publiciteradio',
            name='fin',
            field=models.TimeField(default='20:18:08'),
        ),
    ]
