# Generated by Django 3.1.7 on 2022-06-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220626_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='fin',
            field=models.TimeField(default='22:49:17'),
        ),
        migrations.AlterField(
            model_name='programmeradio',
            name='fin',
            field=models.TimeField(default='22:49:17'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='fin',
            field=models.TimeField(default='22:49:17'),
        ),
        migrations.AlterField(
            model_name='publiciteradio',
            name='fin',
            field=models.TimeField(default='22:49:17'),
        ),
        migrations.CreateModel(
            name='TarifRadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.TimeField()),
                ('fin', models.TimeField(default='22:49:17')),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.radio')),
            ],
        ),
        migrations.CreateModel(
            name='TarifChaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.TimeField()),
                ('fin', models.TimeField(default='22:49:17')),
                ('prix', models.IntegerField(blank=True, null=True)),
                ('chaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.chaine')),
            ],
        ),
    ]
