# Generated by Django 3.1.7 on 2022-06-05 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pub_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='date_creation',
        ),
    ]
