# Generated by Django 3.1.7 on 2022-06-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220626_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='publicite',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='publiciteradio',
            name='code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='programme',
            name='fin',
            field=models.TimeField(default='21:12:36'),
        ),
        migrations.AlterField(
            model_name='programmeradio',
            name='fin',
            field=models.TimeField(default='21:12:36'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='fin',
            field=models.TimeField(default='21:12:36'),
        ),
        migrations.AlterField(
            model_name='publiciteradio',
            name='fin',
            field=models.TimeField(default='21:12:36'),
        ),
        migrations.AlterField(
            model_name='tarifchaine',
            name='fin',
            field=models.TimeField(default='21:12:36'),
        ),
        migrations.AlterField(
            model_name='tarifradio',
            name='fin',
            field=models.TimeField(default='21:12:36'),
        ),
    ]
