# Generated by Django 3.1.7 on 2022-07-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220628_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='prix',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='fin',
            field=models.TimeField(default='17:37:29'),
        ),
        migrations.AlterField(
            model_name='programmeradio',
            name='fin',
            field=models.TimeField(default='17:37:29'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='fin',
            field=models.TimeField(default='17:37:29'),
        ),
        migrations.AlterField(
            model_name='publiciteradio',
            name='fin',
            field=models.TimeField(default='17:37:29'),
        ),
        migrations.AlterField(
            model_name='tarifchaine',
            name='fin',
            field=models.TimeField(default='17:37:29'),
        ),
        migrations.AlterField(
            model_name='tarifradio',
            name='fin',
            field=models.TimeField(default='17:37:29'),
        ),
    ]
