# Generated by Django 3.1.7 on 2022-06-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220605_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='date_creation',
            field=models.DateField(default=''),
        ),
    ]
