# Generated by Django 3.1.7 on 2022-06-05 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220605_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub',
            name='date_creation',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
