# Generated by Django 3.1.7 on 2022-06-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20220605_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pub',
            name='date_creation',
        ),
    ]
