# Generated by Django 3.1.7 on 2022-06-05 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_pub_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='date_creation',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
