# Generated by Django 3.1.7 on 2022-06-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220605_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicite',
            name='fin',
            field=models.TimeField(default=''),
        ),
    ]
