# Generated by Django 3.1.7 on 2022-06-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_publicite_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicite',
            name='message',
            field=models.CharField(default='10:10', max_length=12000),
        ),
    ]
