# Generated by Django 3.1.7 on 2022-06-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220606_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicite',
            name='fin',
            field=models.TimeField(default='10:10'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='message',
            field=models.CharField(default='', max_length=12000),
        ),
    ]
