# Generated by Django 3.1.7 on 2022-06-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_publicite_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='fin',
            field=models.TimeField(default='15:19:36'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='fin',
            field=models.TimeField(default='15:19:36'),
        ),
    ]
