# Generated by Django 3.1.7 on 2022-06-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20220606_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programme',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='publicite',
            name='duree',
        ),
        migrations.AlterField(
            model_name='programme',
            name='fin',
            field=models.TimeField(default='15:26:52'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='fin',
            field=models.TimeField(default='15:26:52'),
        ),
    ]
