# Generated by Django 3.1.7 on 2022-06-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20220607_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='famille',
            name='NomAnnonceur',
        ),
        migrations.RemoveField(
            model_name='marche',
            name='NomAnnonceur',
        ),
        migrations.RemoveField(
            model_name='secteur',
            name='NomAnnonceur',
        ),
        migrations.RemoveField(
            model_name='segment',
            name='NomAnnonceur',
        ),
        migrations.AlterField(
            model_name='programme',
            name='fin',
            field=models.TimeField(default='22:09:03'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='fin',
            field=models.TimeField(default='22:09:03'),
        ),
    ]
