# Generated by Django 3.1.7 on 2022-06-07 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20220607_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicite',
            name='famille',
        ),
        migrations.RemoveField(
            model_name='publicite',
            name='marche',
        ),
        migrations.RemoveField(
            model_name='publicite',
            name='secteur',
        ),
        migrations.RemoveField(
            model_name='publicite',
            name='segment',
        ),
        migrations.AddField(
            model_name='pub',
            name='famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.famille'),
        ),
        migrations.AddField(
            model_name='pub',
            name='marche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.marche'),
        ),
        migrations.AddField(
            model_name='pub',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.secteur'),
        ),
        migrations.AddField(
            model_name='pub',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.segment'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='fin',
            field=models.TimeField(default='22:40:50'),
        ),
        migrations.AlterField(
            model_name='publicite',
            name='fin',
            field=models.TimeField(default='22:40:50'),
        ),
    ]
